Fix build failures in update methods
This fixes build errors like the following:

    In file included from /build/imu_tools-release-release-rolling-rviz_imu_plugin-2.2.3-1/src/imu_display.cpp:31:
    /build/imu_tools-release-release-rolling-rviz_imu_plugin-2.2.3-1/src/imu_display.h:72:10: error: 'void rviz_imu_plugin::ImuDisplay::update(float, float)' marked 'override', but does not override
       72 |     void update(float dt, float ros_dt) override;
          |          ^~~~~~

The update(float, float) method was replaced with
update(std::chrono::duration, std::chrono::duration) in
https://github.com/ros2/rviz/pull/1533.